title: Erick Sasse
email: esasse@gmail.com
description: Desenvolvimento de software, tecnologia e afins
url: http://ericksasse.com.br
twitter_username: esasse

# GitHub
github_username:  esasse
github_repo_url: https://github.com/esasse/esasse.github.io/
github_repo_branch: master

highlighter: rouge
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Erick Sasse"

plugins:
  - jekyll-sitemap
  - jekyll-feed

exclude: [vendor]
