title: Erick Sasse
url: http://ericksasse.com

highlighter: rouge
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Erick Sasse"

plugins:
  - jekyll-sitemap
  - jekyll-feed

exclude: [vendor]
